-- CourseHub
-- Migration: create declarations
-- Date: 2026-08-16
-- Feature: academic documents (declarations and certificates) -- Fase 2
-- MySQL: 8.0+
--
-- Purpose:
--   Domain entity for the three academic declaration types
--   (enrollment / attendance / completion). Distinct from
--   generated_documents (Fase 0): this table is the durable academic
--   fact/audit record (who, which enrollment, which period, public
--   verification code, revocation trail); generated_documents is the
--   PDF generation/storage record for the resulting file. A row here
--   points at generated_documents.id once the PDF is ready, not the
--   other way around.
--
--   Replaces an untracked, unreferenced, empty legacy `declarations`
--   table dropped in 20260816_003 (see that migration's header for
--   the reasoning) -- it stored rendered title/body text directly and
--   had no way to link to a real generated PDF or a public
--   verification code, incompatible with the shared document
--   infrastructure built in Fase 0.
--
-- Domain rules:
--   - verification_code is opaque and random (12 chars, generated by
--     backend/services/academic/-- never sequential, never the row's
--     own id), unique, and never reused -- a reissue always mints a
--     new code and chains back via superseded_by_declaration_id,
--     never mutates or recycles the old one.
--   - A declaration is immutable once issued; revocation records who/
--     when/why but never deletes the row (status flips to 'revoked',
--     history stays queryable).
--   - reference_period_start/end are only populated for
--     declaration_type = 'attendance' (a declaration about a specific
--     date range of presence); NULL for 'enrollment'/'completion'.
--
-- Important:
--   This is a one-time migration. Do not execute it twice.
--   Requires a DB user with DDL privileges (CREATE).
--   Must run after 20260816_003 (frees the `declarations` table name)
--   and after 20260816_002 (generated_documents must already exist
--   for the FK below).

USE coursehub_escola;

CREATE TABLE declarations (
  id INT NOT NULL AUTO_INCREMENT,

  declaration_type ENUM('enrollment', 'attendance', 'completion') NOT NULL,
  enrollment_id INT NOT NULL,

  reference_period_start DATE NULL,
  reference_period_end DATE NULL,

  generated_document_id BIGINT UNSIGNED NULL,
  verification_code CHAR(12) NOT NULL,

  status ENUM('active', 'revoked') NOT NULL DEFAULT 'active',

  requested_by_user_id INT NULL,

  revoked_at DATETIME NULL,
  revoked_by_user_id INT NULL,
  revocation_reason VARCHAR(500) NULL,

  superseded_by_declaration_id INT NULL,

  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),

  UNIQUE KEY uq_declarations_verification_code (verification_code),
  KEY idx_declarations_enrollment (enrollment_id, declaration_type),

  CONSTRAINT fk_declarations_enrollment
    FOREIGN KEY (enrollment_id)
    REFERENCES enrollments(id)
    ON DELETE RESTRICT,

  CONSTRAINT fk_declarations_document
    FOREIGN KEY (generated_document_id)
    REFERENCES generated_documents(id)
    ON DELETE SET NULL,

  CONSTRAINT fk_declarations_requested_by
    FOREIGN KEY (requested_by_user_id)
    REFERENCES users(id)
    ON DELETE SET NULL,

  CONSTRAINT fk_declarations_revoked_by
    FOREIGN KEY (revoked_by_user_id)
    REFERENCES users(id)
    ON DELETE SET NULL,

  CONSTRAINT fk_declarations_superseded
    FOREIGN KEY (superseded_by_declaration_id)
    REFERENCES declarations(id)
    ON DELETE SET NULL
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- POST-MIGRATION VERIFICATION
-- -----------------------------------------------------------------------------

SELECT 'declarations' AS table_name, COUNT(*) AS row_count FROM declarations;
